version: '2.1'
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: clinica
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

  clinica:
    build: .
    ports:
      - '3000:3000'
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - files:/clinica/public/uploads
    
volumes:
  files:
  mongodbdata: